// Composite meeting flow: ONE approval card -> calendar event (+Meet link),
// optional extra Gmail, then a WhatsApp template ping per mobile attendee.
// Steps are called directly (googleFetch / sendTemplate), not via the
// calendar.createEvent and whatsapp.send actions, so the user approves the
// whole plan once instead of once per side effect.
import { randomUUID } from "node:crypto";
import { defineAction } from "@agent-native/core/action";
import { z } from "zod";
import { audit } from "../../server/lib/audit.js";
import { requireApproval } from "../../server/lib/approvals.js";
import {
  buildMimeMessage,
  CALENDAR_BASE,
  GMAIL_BASE,
  googleFetch,
  isDryRun,
} from "../../server/lib/google-auth.js";
import type { ActionResult } from "../../server/lib/types.js";
import { sendTemplate } from "../../server/lib/whatsapp-client.js";
import { extractMeetLink } from "../calendar.createEvent.js";
import { e164Phone } from "../whatsapp/send.js";

function defaultTimeZone(e: NodeJS.ProcessEnv = process.env): string {
  return e.DEFAULT_TIMEZONE ?? "Asia/Kolkata";
}

function templateName(e: NodeJS.ProcessEnv = process.env): string {
  return e.MEETING_WHATSAPP_TEMPLATE ?? "meeting_invite";
}

function templateLang(e: NodeJS.ProcessEnv = process.env): string {
  return e.MEETING_WHATSAPP_TEMPLATE_LANG ?? "en_US";
}

/** IANA zones only: Intl throws on anything else, so check it in zod. */
const ianaZone = z.string().min(1).refine(
  (tz) => {
    try {
      new Intl.DateTimeFormat("en", { timeZone: tz });
      return true;
    } catch {
      return false;
    }
  },
  { message: "Must be an IANA time zone, e.g. Asia/Kolkata" },
);

const isoDate = z.string().refine((v) => !Number.isNaN(new Date(v).getTime()), {
  message: "Must be an ISO date/time, e.g. 2026-10-02T16:00:00+05:30",
});

export const meetingAttendee = z.object({
  name: z.string().min(1).describe("How the attendee is addressed in the WhatsApp message"),
  email: z.string().email().optional().describe("Gets the Google Calendar invite by email"),
  whatsapp: e164Phone
    .optional()
    .describe("Mobile number in E.164; gets the WhatsApp template ping"),
});

/** "Thursday, 2 October 2026, 16:00 IST" in the given zone. Pure — tested. */
export function humanTime(iso: string, timeZone: string): string {
  return new Intl.DateTimeFormat("en-GB", {
    timeZone,
    dateStyle: "full",
    timeStyle: "short",
  }).format(new Date(iso));
}

export default defineAction({
  description:
    "Schedule a meeting with a Google Meet link and notify everyone in one step: creates the calendar event (emails invites), optionally sends an extra Gmail with your message, and sends a WhatsApp template ping to attendees with a mobile number. Use when the user asks to set up a call and let people know. One approval covers the whole plan; DRY_RUN only shows the plan.",
  mcpTool: true,
  schema: z.object({
    title: z.string().min(1).describe("Event title"),
    start: isoDate.describe("Start, ISO with offset (e.g. 2026-10-02T16:00:00+05:30) or local time read in timeZone"),
    durationMinutes: z.number().int().min(5).max(1440).default(30).describe("Meeting length"),
    timeZone: ianaZone.optional().describe("IANA zone the meeting is scheduled in; defaults to DEFAULT_TIMEZONE"),
    attendees: z
      .array(meetingAttendee)
      .min(1)
      .describe("Who to invite; email gets the calendar invite, whatsapp gets the template ping"),
    sendEmailInvite: z
      .boolean()
      .default(true)
      .describe("Let Google email the calendar invites (sendUpdates=all)"),
    message: z
      .string()
      .max(4000)
      .optional()
      .describe("Extra note to send by Gmail; needs sendEmailInvite"),
  }),
  // Deliberately NOT `needsApproval: true`: that framework gate would prompt
  // with the raw input only, and the input is not the full plan (the WhatsApp
  // numbers and message text are derived after the event insert). The single
  // requireApproval() below is the one card, and it shows every side effect.
  run: async (args): Promise<ActionResult> => {
    const tz = args.timeZone ?? defaultTimeZone();
    const startMs = new Date(args.start).getTime();
    const start = new Date(startMs).toISOString();
    const end = new Date(startMs + args.durationMinutes * 60_000).toISOString();
    const emails = args.attendees
      .map((a) => a.email)
      .filter((e): e is string => Boolean(e));
    const mobiles = args.attendees.filter((a) => a.whatsapp !== undefined);

    // Everything the approver needs to see. The Meet link is generated BY the
    // event insert, so it cannot be in the card — it is named, not chosen.
    const plan = {
      event: { title: args.title, start, end, timeZone: tz, addMeet: true },
      invites: args.sendEmailInvite ? emails : [],
      extraGmail: args.sendEmailInvite && args.message ? emails : [],
      whatsapp: mobiles.map((a) => ({
        to: a.whatsapp as string,
        attendee: a.name,
        template: templateName(),
      })),
      message: args.message ?? null,
    };

    if (isDryRun()) {
      console.log(
        `[meetings:dry-run] ${JSON.stringify({ ...plan, meetLink: "generated by the event insert" })}`,
      );
      const outcome = { ok: true, dryRun: true, plan };
      await audit({ actor: "agent", action: "meetings.scheduleAndNotify", input: plan, outcome });
      return { ok: true, data: outcome };
    }

    const decision = await requireApproval({
      action: "meetings.scheduleAndNotify",
      summary:
        `Create "${args.title}" ${start} -> ${end} (${tz}) with Meet link; ` +
        `${emails.length ? `invite ${emails.join(", ")} by email; ` : ""}` +
        `${args.message ? `email the note "${args.message}"; ` : ""}` +
        `${mobiles.length ? `WhatsApp ${templateName()} to ${mobiles.map((a) => a.whatsapp).join(", ")}` : ""}`,
      payload: plan,
    });
    if (!decision.approved) {
      const error = `Not approved (${decision.reason ?? "denied"}). Nothing was scheduled.`;
      await audit({
        actor: "agent",
        action: "meetings.scheduleAndNotify",
        input: plan,
        outcome: { ok: false, error },
      });
      return { ok: false, error };
    }

    // (1) event + Meet link. Google emails the invites via sendUpdates.
    let event: ActionResult<{ eventId: string; htmlLink?: string; meetLink?: string }>;
    try {
      const inserted = (await googleFetch(
        `${CALENDAR_BASE}/calendars/primary/events?conferenceDataVersion=1&sendUpdates=${args.sendEmailInvite ? "all" : "none"}`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            summary: args.title,
            start: { dateTime: start, timeZone: tz },
            end: { dateTime: end, timeZone: tz },
            attendees: emails.map((email) => ({ email })),
            conferenceData: {
              createRequest: {
                requestId: randomUUID(),
                conferenceSolutionKey: { type: "hangoutsMeet" },
              },
            },
          }),
        },
      )) as {
        id?: string;
        htmlLink?: string;
        hangoutLink?: string;
        conferenceData?: { entryPoints?: Array<{ entryPointType?: string; uri?: string }> };
      };
      event = {
        ok: true,
        data: {
          eventId: inserted.id ?? "unknown",
          htmlLink: inserted.htmlLink,
          meetLink: extractMeetLink(inserted),
        },
      };
    } catch (err) {
      // Nothing else can run without the event, so stop here.
      const error = err instanceof Error ? err.message : String(err);
      await audit({
        actor: "agent",
        action: "meetings.scheduleAndNotify",
        input: plan,
        outcome: { ok: false, error },
      });
      return { ok: false, error: `Calendar event failed, nothing else was sent: ${error}` };
    }

    // (2) extra Gmail. Google already sent the invite; this carries `message`.
    let email: { sent: boolean; messageId?: string; error?: string } = { sent: false };
    if (args.message && args.sendEmailInvite && emails.length > 0) {
      try {
        const sent = (await googleFetch(`${GMAIL_BASE}/messages/send`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(
            buildMimeMessage({
              to: emails,
              subject: args.title,
              body: args.message,
            }),
          ),
        })) as { id?: string };
        email = { sent: true, messageId: sent.id ?? "unknown" };
      } catch (err) {
        email = { sent: false, error: err instanceof Error ? err.message : String(err) };
      }
    }

    // (3) one WhatsApp template per mobile attendee, in the meeting time zone.
    const when = humanTime(start, tz);
    const whatsappResults: Array<{
      to: string;
      ok: boolean;
      messageId?: string;
      error?: string;
    }> = [];
    for (const a of mobiles) {
      const to = a.whatsapp as string;
      try {
        const res = await sendTemplate(to, templateName(), templateLang(), [
          a.name,
          args.title,
          when,
          event.data?.meetLink ?? "(no Meet link)",
        ]);
        whatsappResults.push(
          res.ok
            ? { to, ok: true, messageId: res.data?.messageId }
            : { to, ok: false, error: res.error ?? "unknown error" },
        );
      } catch (err) {
        whatsappResults.push({
          to,
          ok: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    }

    // (4) report everything: what worked is never hidden by what failed.
    const failures = whatsappResults.filter((r) => !r.ok);
    const report = {
      event: event.data,
      invites: plan.invites,
      email,
      whatsappResults,
      partial: failures.length > 0 || Boolean(email.error),
    };
    await audit({ actor: "agent", action: "meetings.scheduleAndNotify", input: plan, outcome: report });
    return { ok: !report.partial, data: report, ...(report.partial ? { error: "Some steps failed; see data for what succeeded." } : {}) };
  },
});